name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Install Node with Mise
        uses: jdx/mise-action@v2

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v4
        with:
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Create Release Pull Request / NPM Publish
        uses: changesets/action@v1
        with:
          publish: npm run publish-changeset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
